$(document).ready(function () {

    $(".pflower-img").hover(function () {
        console.log('pflower-img hover!!!!!');
        $(".room-img").toggle()
        $(".blue-ruby").toggle()
        $(".smallruby-img").toggle()
        $(".tank").toggle()
        $(".yellow-lily").toggle()


    })

    $(".room-img").hover(function () {
        console.log('room-img hover!!!!!');
        $(".wall-block img").toggle()
        $(".orange-block img").toggle()
        $(".pier-block img").toggle()
        $(".table-block img").toggle()
        $(".lexi-quote img").toggle()
        $(".description").toggle()
    })
    $(".ruby-img").hover(function () {
        console.log('HI HELLO HIIII ruby-img hover!!!!!');

        $(".picnic").toggle()
        $(".room-img").toggle()
        $(".blue-ruby").toggle()
        $(".smallruby-img").toggle()
        $(".tank").toggle()
        $(".yellow-lily").toggle()
        $(".flower").toggle()
        $(".sky-img").toggle()
        $(".lexi-img").toggle()
        $(".food img").toggle()
        $(".birthday img").toggle()
    })

    $(".lexi-img").hover(function () {
        $(".wall-block img").toggle()
        $(".orange-block img").toggle()
        $(".pier-block img").toggle()
        $(".ruby img").toggle()
        $(".drink img").toggle()
        $(".birthday img").toggle()
        $("#food-id").toggle()
    })
    $(".rose-close img").hover(function () {
        $(".wall-block img").toggle()
        $(".orange-block img").toggle()
        $(".pier-block img").toggle()
        $(".ruby-img").toggle()
        $(".drink img").toggle()
        $(".birthday img").toggle()
        $(".room-img").toggle()
        $(".blue-ruby").toggle()
        $(".smallruby-img").toggle()
        $(".tank").toggle()
        $(".yellow-lily").toggle()
        $(".pflower-img").toggle()
        $(".sky-img").toggle()
        $(".lexi-img").toggle()
        $(".picnic img").toggle()
        $(".fish img").toggle()
        $(".plant img").toggle()
        $(".lexi-quote img").toggle()
        $(".description").toggle()
        $(".table-block img").toggle()
        $(".pflower-img").toggle()
        $(".curtain-close img").toggle()
        $(".lily-close").toggle()
        $(".banner img").toggle()
        $(".pattern img").toggle()
        $(".pink img").toggle()
        $(".second-september").toggle()
        $("h1").toggle()
        $(".food-img").toggle()
    })
    $(".fish img").hover(function () {
        $(".wall-block img").toggle()
        $(".orange-block img").toggle()
        $(".pier-block img").toggle()
        $(".ruby-img").toggle()
        $(".drink img").toggle()
        $(".birthday img").toggle()
        $(".room-img").toggle()
        $(".blue-ruby").toggle()
        $(".smallruby-img").toggle()
        $(".tank").toggle()
        $(".yellow-lily").toggle()
        $(".pflower-img").toggle()
        $(".sky-img").toggle()
        $(".lexi-img").toggle()
        $(".picnic img").toggle()
        $(".plant img").toggle()
        $(".table-block img").toggle()
        $(".pflower-img").toggle()
        $(".curtain-close img").toggle()
        $(".lily-close").toggle()
        $(".banner img").toggle()
        $(".pattern img").toggle()
        $(".pink img").toggle()
        $(".food-img").toggle()
        $(".rose-close img").toggle()
        $(".second-september").toggle()
        $("h1").toggle()

    })


})